### ISSUE TITLE
File Missing

### ISSUE THREAD

**Issue by ivandrofly** [xylographe/SE-WordListValidator#1]
@xylographe I think you miss to push `Assembly.cs`

**Comment by xylographe** [comment]
`SE-WordListValidator\Properties\AssemblyInfo.cs` is generated when the project is build (by running `build.ps1`, or by running `MSBuild` directly or from within VS). This file cannot be part of the git controlled files, because the build number changes after each commit. Therefore, it is included in `.gitignore`.

Where Subtitle Edit uses the separate UpdateAssemblyInfo project, SE-WLV invokes `build.ps1 -UpdateAssemblyInfo` from [SE-WordListValidator.csproj.
](https://github.com/xylographe/SE-WordListValidator/blob/master/SE-WordListValidator/SE-WordListValidator.csproj#L139)
Perhaps, there is a problem with that command? (obviously, it works for me, I can only guess).

**Comment by ivandrofly** [comment]
I have already added the file, just thought you missed it or something like that  :wink:
